// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"go-dbsqlc/db"
	"go-dbsqlc/internal/config"
	"go-dbsqlc/internal/handler"
	"go-dbsqlc/internal/repository"
	"go-dbsqlc/internal/service"
	"go-dbsqlc/internal/validator"
	"log/slog"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*App, func(), error) {
	validate := validator.NewValidator()
	logger := slog.Default()
	sqlDB, cleanup, err := config.NewMySQL(cfg)
	if err != nil {
		return nil, nil, err
	}
	queries := db.New(sqlDB)
	userRepository := repository.NewUserRepository(sqlDB, queries)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(validate, logger, userService)
	productRepository := repository.NewProductRepository(queries)
	productService := service.NewProductService(logger, productRepository)
	productHandler := handler.NewProductHandler(validate, logger, productService)
	handlersParam := handler.HandlersParam{
		User:    userHandler,
		Product: productHandler,
	}
	handlers := handler.NewHandlers(handlersParam)
	app := NewApp(cfg, handlers)
	return app, func() {
		cleanup()
	}, nil
}
