// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Product struct {
	ID        int64
	Name      string
	Price     int32
	CreatedAt sql.NullTime
}

type User struct {
	ID        int64
	Name      string
	Email     string
	CreatedAt sql.NullTime
	AvatarUrl sql.NullString
}
