// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Product struct {
	ID        int64
	Name      string
	Price     int32
	CreatedAt sql.NullTime
	IsActive  bool
	SalePrice int32
	Sku       string
}

type User struct {
	ID        int64
	Name      string
	Email     string
	CreatedAt sql.NullTime
	AvatarUrl sql.NullString
}

type UserAddress struct {
	ID        int32
	UserID    int64
	Street    string
	City      string
	Country   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
