// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
	"database/sql"
)

const createProduct = `-- name: CreateProduct :execresult
INSERT INTO
    products (name, price, is_active, sale_price)
VALUES
    (?, ?, ?,?)
`

type CreateProductParams struct {
	Name      string
	Price     int32
	IsActive  bool
	SalePrice int32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProduct,
		arg.Name,
		arg.Price,
		arg.IsActive,
		arg.SalePrice,
	)
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE
    id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT
    id, name, price, created_at, is_active, sale_price
FROM
    products
WHERE
    id = ?
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.CreatedAt,
		&i.IsActive,
		&i.SalePrice,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT
    id, name, price, created_at, is_active, sale_price
FROM
    products
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.CreatedAt,
			&i.IsActive,
			&i.SalePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET
    name = ?,
    price = ?,
    is_active = ?,
    sale_price = ?
WHERE
    id = ?
`

type UpdateProductParams struct {
	Name      string
	Price     int32
	IsActive  bool
	SalePrice int32
	ID        int64
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.Name,
		arg.Price,
		arg.IsActive,
		arg.SalePrice,
		arg.ID,
	)
	return err
}
