// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_address.sql

package db

import (
	"context"
	"database/sql"
)

const createUserAddress = `-- name: CreateUserAddress :execresult
INSERT INTO
    user_addresses (user_id, street, city, country)
VALUES
    (?, ?, ?, ?)
`

type CreateUserAddressParams struct {
	UserID  int64
	Street  string
	City    string
	Country string
}

func (q *Queries) CreateUserAddress(ctx context.Context, arg CreateUserAddressParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserAddress,
		arg.UserID,
		arg.Street,
		arg.City,
		arg.Country,
	)
}

const deleteAddressesByUserID = `-- name: DeleteAddressesByUserID :exec
DELETE FROM user_addresses
WHERE
    user_id = ?
`

func (q *Queries) DeleteAddressesByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAddressesByUserID, userID)
	return err
}

const getAddressesByUserID = `-- name: GetAddressesByUserID :many
SELECT
    id, user_id, street, city, country, created_at, updated_at
FROM
    user_addresses
WHERE
    user_id = ?
`

func (q *Queries) GetAddressesByUserID(ctx context.Context, userID int64) ([]UserAddress, error) {
	rows, err := q.db.QueryContext(ctx, getAddressesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAddress
	for rows.Next() {
		var i UserAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Street,
			&i.City,
			&i.Country,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserAddresses = `-- name: GetAllUserAddresses :many
SELECT
    id, user_id, street, city, country, created_at, updated_at
FROM
    user_addresses
`

func (q *Queries) GetAllUserAddresses(ctx context.Context) ([]UserAddress, error) {
	rows, err := q.db.QueryContext(ctx, getAllUserAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAddress
	for rows.Next() {
		var i UserAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Street,
			&i.City,
			&i.Country,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAddress = `-- name: UpdateUserAddress :exec
UPDATE user_addresses
SET
    user_id = ?,
    street = ?,
    city = ?,
    country = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
    AND user_id = ?
`

type UpdateUserAddressParams struct {
	UserID   int64
	Street   string
	City     string
	Country  string
	ID       int32
	UserID_2 int64
}

func (q *Queries) UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAddress,
		arg.UserID,
		arg.Street,
		arg.City,
		arg.Country,
		arg.ID,
		arg.UserID_2,
	)
	return err
}
